### ISSUE TITLE
display error at zoom

### ISSUE THREAD

**Issue by danbjoseph** [PhilippineRedCross/yolanda_recovery#2]
zooming in to a more detailed admin level no longer displays correctly
**now:**

![screen shot 2015-09-21 at 11 24 35 am](https://cloud.githubusercontent.com/assets/4806884/9997098/55621b42-6058-11e5-9460-6299fe6d198a.png)

---

**before:**

![screen shot 2015-09-21 at 11 24 49 am](https://cloud.githubusercontent.com/assets/4806884/9997099/5763b720-6058-11e5-8094-4d49df8ee2c8.png)

**Comment by charlesranby** [comment]
The mapped group variable ids corrected.
